name: 'Автотесты с Allure отчётом'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Получение кода из репозитория
      uses: actions/checkout@v4
    
    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Настройка Chrome и ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Запуск тестов с Allure
      run: |
        pytest --alluredir=allure-results
      continue-on-error: true
    
    - name: Получение истории Allure
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Генерация Allure отчёта
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20
    
    - name: Развёртывание на GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        
    - name: Сохранение артефактов (результаты)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30
        
    - name: Сохранение отчёта
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-history/
        retention-days: 30