name: 'Selenium Tests with Allure Report'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.3 selenium==4.15.2 allure-pytest==2.13.2
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Run tests (continue on failure)
      run: |
        mkdir -p allure-results
        python -m pytest --alluredir=allure-results -v || echo "Tests completed with some failures"
    
    - name: Setup Java for Allure
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Download and setup Allure
      run: |
        curl -o allure-2.24.1.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
        tar -zxf allure-2.24.1.tgz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure --version
    
    - name: Generate Allure report
      run: |
        # Создаём базовые результаты если их нет
        if [ ! "$(ls -A allure-results)" ]; then
          echo "No test results found, creating dummy results"
          mkdir -p allure-results
          echo '{"uuid":"dummy"}' > allure-results/dummy.json
        fi
        
        # Генерируем отчёт
        allure generate allure-results --clean -o allure-report
        
        # Проверяем что отчёт создался
        ls -la allure-report/
    
    - name: Create index redirect
      run: |
        if [ ! -f allure-report/index.html ]; then
          echo "Creating index.html redirect"
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=./index.html"></head><body>Redirecting...</body></html>' > allure-report/index.html
        fi
    
    - name: Debug - List report contents
      run: |
        echo "Report directory contents:"
        find allure-report -type f | head -20
    
    - name: Deploy to GitHub Pages (force push)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy Allure report'
    
    - name: Upload artifacts for debugging
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-and-report
        path: |
          allure-results/
          allure-report/
        retention-days: 7